In [1]:
import math
import random
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

<h2 style="font-size:2rem;color:black;">Math Notes</h2>

Dictionary:<br>

Affine Function -> A linear function that is shifted on the y axis by a constant c. i.e. mx+c

<h3 style="color:gray;">Linear Algebra (Solving Linear Equations Using Gaussian Elimination)</h3>

In [8]:
#This is to generate equations to test the code below.
no = int(input("Number of equations: "))
values = []
coefficients = [] #This is different from the one below. Instead of coefficients of a specific one, this is the coefficients of one equation.
results = []

for x in range(no):
    values.append(random.randrange(-10, 10))

for x in range(no):
    tempCoef = []
    for y in range(no):
        tempCoef.append(random.randrange(-25, 25))
    coefficients.append(tempCoef)
    tempRes = 0 
    for z in range(no):
        tempRes = tempRes + tempCoef[z] * values[z]
    results.append(tempRes)

print(values)
print(coefficients)
print(results)

Number of equations:  5


[6, -10, -4, -10, 8]
[[-22, -4, -15, 10, -14], [4, 22, -10, -16, 5], [0, -14, -16, -7, 1], [-17, -14, -15, 14, -11], [-20, -5, 20, 15, -20]]
[-244, 44, 282, -130, -460]


In [10]:
dimA = input(f"Enter the equation count you want to solve (Equation count must be equal to the variable count): ->")
while True:
    try:
        dimA = int(dimA)
        break
    except ValueError:
        dimA = input(f"Enter the equation count you want to solve (Equation count must be equal to the variable count): ->")

A = np.zeros((dimA, dimA + 1), dtype=np.float64)

class MatrixSingular(Exception):
    def __init__(self):
        super().__init__()
        self.message = "The determinant of the coefficient matrix is 0 (It has either none or infinite solutions.), try a different matrix."
    def __str__(self):
        return f"{self.message}"

def inputStuff():
    print(f"Please input the following values according to your linear equations in form: ax1+bx2+cx3+...+dxn=e")
    cols = []
    for x in range(dimA):
        cols.append(input(f"Enter x{x+1}'s coefficients (Leave one space between the values, if not recognized, the value will be count as 0) -> ").split(" "))
    cols.append(input(f"Enter the constants (Leave one space between the values, if not recognized, the value will be count as 0) -> ").split(" "))
    for y in range(A.shape[1]):
        for x in range(cols[y].__len__()):
            try:
                A[x, y] = float(cols[y][x])
            except ValueError:
                A[x, y] = 0
            except IndexError:
                pass

def reduceRow(row, dimension):
    if dimension <= row: return
    print(f"ELIMINATION Step {row+1}:")
    print(A)
    if row == 0: pass
    else:
        for x in range(row):
            A[row] = A[row] - A[row, x] * A[x]
    for y in range(1, A.shape[0] - 1):
        if A[row, row] == 0:
            A[row] = A[row] + A[y+1]
        else: break
    if A[row, row] == 0:
        raise MatrixSingular()
        return
    A[row] = A[row] / A[row, row]
    reduceRow(row+1, dimension)

def bsubstitute():
    for x in range(dimA - 1):
        for y in range(x + 1, dimA):
            A[x] = A[x] - A[y] * A[x, y]

def performGaussian():
    inputStuff()
    reduceRow(0, dimA)
    print(f"BACK SUBSTITUTION")
    bsubstitute()
    print(A)

performGaussian()
for x in range(dimA):
    print(f"x{x+1}={A[:,dimA][x]:.3f}",end=" ")

Enter the equation count you want to solve (Equation count must be equal to the variable count): -> 5


Please input the following values according to your linear equations in form: ax1+bx2+cx3+...+dxn=e


Enter x1's coefficients (Leave one space between the values, if not recognized, the value will be count as 0) ->  -22 4 0 -17 -20
Enter x2's coefficients (Leave one space between the values, if not recognized, the value will be count as 0) ->  -4 22 -14 -14 -5
Enter x3's coefficients (Leave one space between the values, if not recognized, the value will be count as 0) ->  -15 -10 -16 -15 20
Enter x4's coefficients (Leave one space between the values, if not recognized, the value will be count as 0) ->  10 -16 -7 14 15
Enter x5's coefficients (Leave one space between the values, if not recognized, the value will be count as 0) ->  -14 5 1 -11 -20
Enter the constants (Leave one space between the values, if not recognized, the value will be count as 0) ->  -244 44 282 -130 -460


ELIMINATION Step 1:
[[ -22.   -4.  -15.   10.  -14. -244.]
 [   4.   22.  -10.  -16.    5.   44.]
 [   0.  -14.  -16.   -7.    1.  282.]
 [ -17.  -14.  -15.   14.  -11. -130.]
 [ -20.   -5.   20.   15.  -20. -460.]]
ELIMINATION Step 2:
[[ 1.00000000e+00  1.81818182e-01  6.81818182e-01 -4.54545455e-01
   6.36363636e-01  1.10909091e+01]
 [ 4.00000000e+00  2.20000000e+01 -1.00000000e+01 -1.60000000e+01
   5.00000000e+00  4.40000000e+01]
 [ 0.00000000e+00 -1.40000000e+01 -1.60000000e+01 -7.00000000e+00
   1.00000000e+00  2.82000000e+02]
 [-1.70000000e+01 -1.40000000e+01 -1.50000000e+01  1.40000000e+01
  -1.10000000e+01 -1.30000000e+02]
 [-2.00000000e+01 -5.00000000e+00  2.00000000e+01  1.50000000e+01
  -2.00000000e+01 -4.60000000e+02]]
ELIMINATION Step 3:
[[ 1.00000000e+00  1.81818182e-01  6.81818182e-01 -4.54545455e-01
   6.36363636e-01  1.10909091e+01]
 [ 0.00000000e+00  1.00000000e+00 -5.98290598e-01 -6.66666667e-01
   1.15384615e-01 -1.70940171e-02]
 [ 0.00000000e+00 -1.40000000e+01 -1

<h3 style="color:gray;">Linear Algebra (Gram-Schmidt Process for Finding Orthonormal Matrices)</h3>

You can check if the resultant matrix is orthonormal by checking the conditions: <br>
-Its column vectors should be of unit length <br>
-Each column's dot products should be zero

In [14]:
A = np.array([[1, 16, 7, 9], #Input the matrix here. Be careful, Gram-Schmidt is only applicable to square matrices.
             [-2, 8, 1, -7],
             [6, 7, 2, -6],
             [1, 2, 8, -4]], dtype=np.float64)

A[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0])
for x in range(1, A.shape[0]):
    for y in range(x):
        A[:, x] = A[:, x] - (A[:, y] @ A[:, x]) * A[:, y]
    A[:, x] = A[:, x] / np.linalg.norm(A[:, x])
A

array([[ 0.15430335,  0.82698899,  0.09892656,  0.53150091],
       [-0.3086067 ,  0.55834926, -0.21776469, -0.73863831],
       [ 0.9258201 ,  0.03950584, -0.24564091, -0.28452939],
       [ 0.15430335,  0.05267446,  0.93938949, -0.30160116]])

<h3 style="color:gray;">Multivariate Calculus (Newton-Raphson Approximation)</h3>

In [17]:
def func(x):
    return x**2+4*x+4

def dfuncdx(x):
    return 2*x+4

a = float(input("Enter an initial value: ->"))

steps = 0
xi = a
fxi = func(a)
dfxi = dfuncdx(a)
print(xi, fxi, dfxi)

while round(fxi, 12) != 0:
    xi = xi - (fxi/dfxi)
    fxi = func(xi)
    dfxi = dfuncdx(xi)
    print(xi, fxi, dfxi, sep=", ")
    steps += 1

print(steps)


Enter an initial value: -> 2


2.0 16.0 8.0
0.0, 4.0, 4.0
-1.0, 1.0, 2.0
-1.5, 0.25, 1.0
-1.75, 0.0625, 0.5
-1.875, 0.015625, 0.25
-1.9375, 0.00390625, 0.125
-1.96875, 0.0009765625, 0.0625
-1.984375, 0.000244140625, 0.03125
-1.9921875, 6.103515625e-05, 0.015625
-1.99609375, 1.52587890625e-05, 0.0078125
-1.998046875, 3.814697265625e-06, 0.00390625
-1.9990234375, 9.5367431640625e-07, 0.001953125
-1.99951171875, 2.384185791015625e-07, 0.0009765625
-1.999755859375, 5.960464477539063e-08, 0.00048828125
-1.9998779296875, 1.4901161193847656e-08, 0.000244140625
-1.99993896484375, 3.725290298461914e-09, 0.0001220703125
-1.999969482421875, 9.313225746154785e-10, 6.103515625e-05
-1.9999847412109375, 2.3283064365386963e-10, 3.0517578125e-05
-1.9999923706054688, 5.820766091346741e-11, 1.52587890625e-05
-1.9999961853027344, 1.4551915228366852e-11, 7.62939453125e-06
-1.9999980926513672, 3.637978807091713e-12, 3.814697265625e-06
-1.9999990463256836, 9.094947017729282e-13, 1.9073486328125e-06
-1.9999995231628418, 2.2737367544323206e